3 Character에 대한 클래스 추가
donghoony/webp_brick pull request #45
Opened 2022-05-26 19:44 UTC by chamdduk

원래는 Character 클래스를 따로 만들고 그에 대한 자식 클래스로 만들려 했으나
만들다보니 Character 클래스와 Ball 클래스와 겹치는 부분이 많은 것 같아
Ball 클래스의 자식 클래스로 만들었습니다.

2022-05-29 03:51 UTC, donghoony requested changes
추가로 일정 시간이 지나야 능력을 사용할 수 있도록 (클릭 시) 코드를 수정해 주세요!

2022-05-29 03:51 UTC, donghoony commented on BrickBreaker.js
> +		super(speed);
super는 상위 클래스의 constructor를 실행하기 때문에, Ball의 Constructor에 해당하는 인자를 모두 넣어줘야 해요

2022-05-29 03:51 UTC, donghoony commented on BrickBreaker.js
> +	activate() {
`deactivate`의 경우도 만들어 주세요!

2022-05-29 13:57 UTC, chamdduk commented on BrickBreaker.js
> +	activate() {
만들었습니다!

2022-05-29 13:58 UTC, donghoony commented on BrickBreaker.js
> +	activate() {
`Ball` 생성자대로 `super`를 call해줘야 합니다

2022-05-29 14:07 UTC, chamdduk commented on BrickBreaker.js
> +	activate() {
생성자 부분 다시 수정했습니다!

2022-05-30 06:37 UTC, donghoony approved these changes

2022-05-30 06:37 UTC, merged